version: '3.8'

services:
  # This service handles wildcard subdomain requests as a fallback
  wildcard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: captuvix-wildcard
    # Use a default port that's not likely to conflict with other services
    ports:
      - "8081:80"  # Map host port 8081 to container port 80
    restart: unless-stopped
    # For production, you might want to set environment variables
    environment:
      - NGINX_HOST=captuvix.com
      - NGINX_PORT=80

    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    # Add labels for traefik if needed (commented out by default)
    labels:
      - "traefik.enable=false"  # Enable to use with Traefik
      # Uncomment the following in production to use with Traefik
      # - "traefik.http.routers.wildcard.rule=HostRegexp(`{subdomain:[a-z0-9-]+}.captuvix.com`)"
      # - "traefik.http.routers.wildcard.priority=1"  # Lower priority than main app
      # - "traefik.http.services.wildcard.loadbalancer.server.port=80"

  # Example of Traefik for production DNS wildcard management
  # traefik:
  #   image: traefik:v2.9
  #   container_name: captuvix-traefik
  #   command:
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"
  #     - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
  #     - "--certificatesresolvers.myresolver.acme.email=your-email@example.com"
  #     - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  #     - "--certificatesresolvers.myresolver.dnschallenge.provider=cloudflare"  # For wildcard certs
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "./letsencrypt:/letsencrypt"
  #   environment:
  #     - "CF_API_EMAIL=your-cloudflare-email@example.com"
  #     - "CF_API_KEY=your-cloudflare-api-key"
  #   restart: unless-stopped

  # Uncomment below to connect with the main web application
  # web:
  #   image: captuvix-web:latest
  #   container_name: captuvix-web
  #   restart: unless-stopped
  #   ports:
  #     - "8080:80"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.web.rule=Host(`captuvix.com`) || Host(`www.captuvix.com`)"
  #     - "traefik.http.routers.web.priority=100"  # Higher priority than wildcard
  #     - "traefik.http.services.web.loadbalancer.server.port=80"

networks:
  default:
    name: captuvix-network